[bugfix] Pin gcloud version, use ChromeForTesting, download GeckoDriver manually (#4465)
* [bugfix] Use latest java for datastore

Currently, CI is broken because the latest datastore emulator version
now requires java 21+

The message is:
ERROR: (gcloud.beta.emulators.datastore.start) The java executable on your PATH is not a Java 21+ JRE. The Google Cloud Datastore emulator requires a Java 21+ JRE installed and on your system PATH

The latest version of java with LTS is 21 (25 comes out soon though)

This change modifies the version to install 21 instead of 11.

* use cft and revert java

* try using one installation

* fix new geckodriver installation